### ISSUE TITLE
Relation between card serial number and Volumio playlists

### ISSUE THREAD

**Issue by midre** [edmw/volumio-diy#5]
Hello,

At first: Thank you for this wonderful Projekt. This is, what I have searched for a long time.

I am a nembie in Raspberry and Programming. What I don't understand is, how the connection between the card numbers and the playlists is working. Is there a database wehre you have to innerset this data? 

Greetings from Marburg
Micha

**Comment by edmw** [comment]
(English below).

Hallo Micha,
ich vermute ich kann Dir auch auf deutsch antworten?

Das Skript macht nach dem Lesen der Karte tatsächlich (ziemlich stumpfsinnig) einen Aufruf der Funktion:

spiele_playlist_mit_dem_namen(hier_nummer_der_karte_einsetzen)

Wenn es eine Playlist mit dem passenden Namen gibt, spielt Volumio diese ab, falls nicht, passiert einfach gar nichts. Das bedeutet - wenn das Skript einmal eingerichtet ist - wird eine neue Karte einfach dadurch aktiviert, dass man in der Weboberfläche von Volumio eine neue Playlist erstellt und für diese Playlist als Namen die Nummer der Karte (gegebenenfalls mit führenden Nullen) gibt.

Das hat den Vorteil, dass es eben keine zusätzliche Datenbank gibt in der Kartennummern mit Playlisten verknüpft werden müssen. Andererseits hat es die Nachteile, dass bereits vorhandene Playlisten nicht benutzt werden können und dass es mit der Zeit ziemlich unübersichtlich wird, da in der Weboberfläche von Volumio die Playlisten dann ja nur mit der Kartennummer als Name aufgelistet werden.

Hoffe die Antwort hilft Dir weiter,
viele Grüße
Michael

English:

The script for reading the tags and controlling Volumio supports playing Volumio playlists at this time. That is, any tag serial number read by the script will be used to send a "play playlist with name 'tag serial number'" command to Volumio. The script doesn't care if there exists a playlist with that name. If there is no such playlist Volumio will just ignore the command and nothing will be played.

My goal was not to be forced to change anything on the command line when adding new tags. Because of that adding a new tag to start playing a playlist works as follows:

1. Open Volumio's web UI (use your computer's browser, you can not do this with the touch display, because you'll have to enter some numbers).
2. Select the desired music to be associated with the new tag and create a new playlist. Volumio will ask for a name for that playlist.
3. Enter the serial number (i.e. '0000640815') of your new tag as name for the new playlist.
4. (If you navigate to Volumio's playlists via the UI you should see the new list now. For example on my player there are various playlists named '0004561234' or '0004728532', and so on. I'll admit this is not very neat but serves my goal).

At this point it should just work. When scanning the new tag its serial will automatically be used to play the new playlist.

**Comment by midre** [comment]
Hallo Michael,

vielen Dank, es klappt, ich bin echt happy! :-)

Grüße
Micha
